# Generated by Django 4.1 on 2022-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_surname', models.CharField(max_length=255)),
                ('employee_hire_date', models.CharField(max_length=255)),
                ('employee_dni', models.CharField(max_length=255)),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]
