# Generated by Django 4.1 on 2022-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjetas',
            fields=[
                ('creditcard_brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creditcard_brand_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marca_tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=255, unique=True)),
                ('card_security_code', models.CharField(max_length=3)),
                ('card_issue_date', models.DateField()),
                ('card_expiration_date', models.DateField()),
                ('card_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
