# Generated by Django 4.1 on 2022-09-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_cliente_cuenta_direccion_tipocliente_tipocuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
