# Generated by Django 4.1 on 2022-09-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
