# Generated by Django 4.1 on 2022-09-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_rename_customer_id_userprofile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
