# Generated by Django 4.1 on 2022-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_rename_customer_userprofile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
