# Generated by Django 4.1 on 2022-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
