# Generated by Django 4.1 on 2022-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_userprofile_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
