# Generated by Django 4.1 on 2022-09-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
