# Generated by Django 4.1 on 2022-09-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
