# Generated by Django 4.1 on 2022-09-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False, 'ordering': ['customer_id']},
        ),
    ]
